# Generated by Django 6.1.1 on 2026-09-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage_temperature',
            field=models.CharField(choices=[('REFRIGERATOR', 'Холодильник (0...+4°C)'), ('ROOM', 'Комнатная температура (+18...+22°C)')], default='REFRIGERATOR', max_length=20, verbose_name='Условия хранения'),
        ),
    ]
